accept-download: true
render-thread-count: 1
metrics: false
scan-for-mod-resources: true

# The folder where bluemap saves data-files
data: "bluemap"

log: {
  file: "bluemap/logs/debug.log"
  #file: "bluemap/logs/debug_%1$tF_%1$tT.log"e
  append: false
}
